// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eysymkeafynkrfxsblhz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5c3lta2VhZnlua3JmeHNibGh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjU3NTYsImV4cCI6MjA2NTUwMTc1Nn0._LugA-7ervnc1ry3qTlX2fc8bzr1dRdBj-Dn4ZSOpwo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);